AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LoginApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: bgb-ceportal-auth-api
      StageName: prod

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bgb-ceportal-auth
      Handler: login.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          USER_POOL_ID: ap-south-1_qmPd7G9Xm
          CLIENT_ID: 7hrt0lrvqsudpqjapgcgodve16
      Policies:
        - AmazonCognitoReadOnly
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref LoginApiGateway
            Path: /login
            Method: POST
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              AllowOrigin: "'*'"
              